---
title: "롤챌린지소개페이지_트러블슛팅"
excerpt: "프로젝트진행"

categories:
  - Categories10

tags:
  - [tag1, tag2]

permalink: /categories10/TroubleShooting/

toc: true
toc_sticky: true

date: 2024-10-07
last_modified_at: 2024-10-07
---

# 🔥 Trouble Shooting!

#### - 챔피언 로테이션 페이지 ( CSR)

: 현재 무료로 플레이 가능한 챔피언들을 표시

#### 문제점 🥵

: 현재 무료로 플레이 가능한 챔피언들을 제공해주는 rotation.api가 id 숫자만을 제공해주고 있었다. 이 숫자들을 처음에는 상세페이지 id에 넣어 정보를 가져올 수 있도록 처리할려고 했었다.
결론적으로 너무 복잡해지는 로직이었다.

#### 해결방법 💪

: 전체 챔피언 리스트를 가져와 rotation.api에 있는 id value값과 전체챔피언리스트에 있는 key값이 일치하는 것만 filter처리하여 데이터를 가져와서 저장하고 저장한 데이터를 사용해 레이아웃을 만들어주었다.

```tsx

const RotationPage = () => {
  const [rotationData, setRotationData] = useState<Champion[]>([]);
  const [loading, setLoading] = useState<boolean>(true);
  const [error, setError] = useState<string>("");

useEffect(() => {
    const fetchRotationData = async () => {
      try {
        // 이번 주 로테이션 데이터
        const res = await getChampionRotation();
        const rotationIds = res.freeChampionIds || [];

        // 전체 데이터
        const championListRes: ChampionListResponse = await fetchChampionList();

        // 로테이션 id와 전체 데이터의 key 비교하여 매칭되는 데이터 추출
        const matchedChampions = Object.keys(championListRes)
          .filter((championKey) =>
            rotationIds.includes(parseInt(championListRes[championKey].key))
          )
          .map((key) => championListRes[key]);

        setRotationData(matchedChampions); // 필터링된 데이터 저장
      } catch (error) {
        setError("error");
      } finally {
        setLoading(false);
      }
    };
    fetchRotationData();
  }, []);

```

# 💥 Trouble Shooting2

6. Custom Error메세지를 표시할 컴포넌트에 적용시켜주기

#### 🥵 문제점

: api를 불러오는 src>utils>serverApi.ts에서 error메세지를 설정해준 후 src>app>champions>page.tsx api를 가져와 레이아웃을 그리는 페이지들이 type오류가 발생했다.

// serverApi.ts

```tsx
// 최신버전
export async function fetchVersion(): Promise<string | CustomError> {
  try {
    const fetchVersion = await fetch(`${BASEURL}/api/versions.json`);
    const versionRes = await fetchVersion.json();
    return versionRes[0]; // 최신 버전 반환
  } catch (error) {
    console.log(error, "Version Error");
    return {
      message: "최신 버전을 가져오는데 실패했습니다.",
    };
  }
}
```

오류화면
![](https://velog.velcdn.com/images/alice0751/post/4c880e5c-a90e-4b3c-ba81-2ae9ce0e3829/image.png)

- 내가 예상한 오류는 이미 아래처럼 data에 type이 설정되어있는데 여기서 설정한 type안에 error처리는 없어서였다.

```tsx

export default async function ChampionPage() {
  const data: ChampionListResponse = await fetchChampionList();

  return (
    <>
      <h1 className="font-extrabold text-3xl text-center mt-12">챔피언목록</h1>
```

- 1차 해결방법
  내가 생각했던 이유가 맞았고 data의 type지정 부분에 CustomError도 함께 추가시켜주니 championList페이지는 에러가 해결되었다!

```tsx

export default async function ChampionPage() {
  const data: ChampionListResponse | CustomError = await fetchChampionList();

  return (
    <>
      <h1 className="font-extrabold text-3xl text-center mt-12">챔피언목록</h1>
      <div className="w-[80%] grid grid-cols-2 sm:grid-cols-3 lg:grid-cols-4 mx-auto mt-12 gap-4">
        <Suspense fallback={<Loading type="page1" />}>
          {Object.values(data).map((champion) => (
            <ChampionCard key={champion.id} champion={champion} />
          ))}
        </Suspense>
      </div>
    </>
  );
```

#### 🥵 또 다른 에러 발생

- 다른 페이지들도 같은 방식으로 해결하면 될 것 같다고 생각했는데 적용시켜보니 또 다른 오류가 발생했다.
  ![](https://velog.velcdn.com/images/alice0751/post/ff22002b-72f6-478d-b378-6b257e1d2fa7/image.png)

#### ✨ 해결방법

- fetch에서 넘어온 data를 items로 저장을 했었다. fetch가 실패해서 데이터가 넘어올경우 message가 넘어오는데 이것이 내가 지정해준 Item[]에 없어서 오류가 발생
- 해결하기 위해서 data안에 message가 있는지 확인하는 로직을 추가해주었다 해결!

```tsx
const ItemPage = async () => {
  const items: Item[] | CustomError = await fetchItem();

  if ("message" in items) {
    return <ErrorComponent error={items} />;
  }
  return (
    <div>
      <h1 className="text-center mt-12 text-3xl font-extrabold">아이템 목록</h1>
      <div className="w-[80%] grid grid-cols-4 sm:grid-cols-6 lg:grid-cols-8 mx-auto mt-12 gap-4">
        <Suspense fallback={<Loading type={"page3"} />}>
          {items?.map((item) => (
            <ItemCard key={item.id} item={item} />
          ))}
        </Suspense>
      </div>
    </div>
  );
};
```

---

# 💥 Trouble Shooting 3 & 코드 리펙토링

#### 🥵 문제점

- rotation페이지는 client side rendering 방식으로 렌더링을 하고 있었고 useEffect()를 통해 페이지가 처음 로드될 때 데이터를 불러올 수 있도록 처리를 했었다. 이 과정에서 useState()를 사용하여 loading과 Error를 따로 처리해주었는데 useQuery를 사용하면 가독성부분과 관리측면에서도 더 용이할 것 같아 리펙토링 하게 되었다.

#### 순서

1. Tanstack Query설치

```tsx
yarn add @tanstack/react-query

```

2. app>providers.tsx생성 후 로직작성

```tsx
"use client";

import {
  isServer,
  QueryClient,
  QueryClientProvider,
} from "@tanstack/react-query";

function makeQueryClient() {
  return new QueryClient({
    defaultOptions: {
      queries: {
        staleTime: 60 * 1000,
      },
    },
  });
}

let browserQueryClient: QueryClient | undefined = undefined;

function getQueryClient() {
  if (isServer) {
    return makeQueryClient();
  } else {
    if (!browserQueryClient) browserQueryClient = makeQueryClient();
    return browserQueryClient;
  }
}

export default function Providers({ children }: { children: React.ReactNode }) {
  const queryClient = getQueryClient();

  return (
    <QueryClientProvider client={queryClient}>{children}</QueryClientProvider>
  );
}
```

3. CSR에서 useQuery사용

- useQuery를 사용해 data, isLoading, error 처리

```tsx
"use client";

import ChampionCard from "@/components/ChampionCard";
import { Champion, ChampionListResponse } from "@/types/Champion";
import { getChampionRotation } from "@/utils/riotApi";
import { fetchChampionList } from "@/utils/serverApi";
import React from "react";
import { useQuery } from "@tanstack/react-query";
import { CustomError } from "@/types/Error";
import ErrorComponent from "../error";

const fetchRotationData = async (): Promise<Champion[]> => {
  // 이번 주 로테이션 데이터
  const res = await getChampionRotation();
  const rotationIds = res.freeChampionIds || [];

  // 전체 데이터
  const championListRes: ChampionListResponse | CustomError =
    await fetchChampionList();

  // CustomError 처리
  if ("message" in championListRes) {
    throw new Error("championList에러입니다");
  }

  // 로테이션 id와 전체 데이터의 key 비교하여 매칭되는 데이터 추출
  return Object.keys(championListRes)
    .filter((championKey) =>
      rotationIds.includes(parseInt(championListRes[championKey].key))
    )
    .map((key) => championListRes[key]);
};

const RotationPage = () => {
  const {
    data: rotationData,
    isLoading,
    error,
  } = useQuery<Champion[], Error>({
    queryKey: ["champitonRotation"],
    queryFn: fetchRotationData,
  });

  if (isLoading) {
    return <div>Loading...</div>;
  }

  if (error) {
    return <ErrorComponent error={error} />;
  }

  return (
    <div>
      <h1 className="font-extrabold text-3xl text-center mt-12 text-red-400">
        이번주 로테이션 챔피언
      </h1>
      <div className="w-[80%] grid grid-cols-2 sm:grid-cols-3 lg:grid-cols-4 mx-auto mt-12 gap-4">
        {rotationData?.map((champion) => (
          <ChampionCard key={champion.key} champion={champion} />
        ))}
      </div>
    </div>
  );
};

export default RotationPage;
```

---

# 🔥 Trouble Shooting 4

# 🌟 배포

![](https://velog.velcdn.com/images/alice0751/post/fb5cdec4-50f9-489b-9e6d-328a36478232/image.png)
💥 문제점
: Rotation페이지에서 loading과 error를 useState()를 사용하여 페이지를 표시해주었는데 배포하는 과정에서 error가 사용되지 않았다는 오류가 떴다. 맨 처음은 이전에 React 작업했을 때와 비슷하게 error를 처리했더니 typescript관련 오류도 함께 발생하였다.

```js
} catch (error)
       { console.log(error,"error발생") }
      } finally {
        setLoading(false);

```

✨ 해결방법
: catch (error: unknown) 구문은 TypeScript의 기능으로, 어떤 타입의 값이 예외로 발생할 수 있는지 인지하게 해준다. 자바스크립트의 에러는 여러 소스에서 발생할 수 있기 때문에, 항상 Error 타입이 아닐 수 있다. instanceof Error를 사용해 에러 타입을 확인함으로써, 존재하지 않을 수 있는 속성에 접근하려고 시도하는 런타임 에러를 방지할 수 있
다.

```js
      } catch (error: unknown) {
        if (error instanceof Error) setError(error.message);
        else {
          setError("Rotation Error");
        }
      } finally {
        setLoading(false);
      }
```
